# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import turnos_pb2 as turnos__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in turnos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TurnoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearTurno = channel.unary_unary(
                '/turnos.TurnoService/CrearTurno',
                request_serializer=turnos__pb2.CrearTurnoRequest.SerializeToString,
                response_deserializer=turnos__pb2.Turno.FromString,
                _registered_method=True)
        self.ObtenerTurno = channel.unary_unary(
                '/turnos.TurnoService/ObtenerTurno',
                request_serializer=turnos__pb2.ObtenerTurnoRequest.SerializeToString,
                response_deserializer=turnos__pb2.Turno.FromString,
                _registered_method=True)
        self.ListarTurnos = channel.unary_unary(
                '/turnos.TurnoService/ListarTurnos',
                request_serializer=turnos__pb2.ListarTurnosRequest.SerializeToString,
                response_deserializer=turnos__pb2.ListaTurnos.FromString,
                _registered_method=True)
        self.ReservarTurno = channel.unary_unary(
                '/turnos.TurnoService/ReservarTurno',
                request_serializer=turnos__pb2.ReservarTurnoRequest.SerializeToString,
                response_deserializer=turnos__pb2.Turno.FromString,
                _registered_method=True)


class TurnoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CrearTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarTurnos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReservarTurno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurnoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearTurno,
                    request_deserializer=turnos__pb2.CrearTurnoRequest.FromString,
                    response_serializer=turnos__pb2.Turno.SerializeToString,
            ),
            'ObtenerTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerTurno,
                    request_deserializer=turnos__pb2.ObtenerTurnoRequest.FromString,
                    response_serializer=turnos__pb2.Turno.SerializeToString,
            ),
            'ListarTurnos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarTurnos,
                    request_deserializer=turnos__pb2.ListarTurnosRequest.FromString,
                    response_serializer=turnos__pb2.ListaTurnos.SerializeToString,
            ),
            'ReservarTurno': grpc.unary_unary_rpc_method_handler(
                    servicer.ReservarTurno,
                    request_deserializer=turnos__pb2.ReservarTurnoRequest.FromString,
                    response_serializer=turnos__pb2.Turno.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turnos.TurnoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('turnos.TurnoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurnoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnos.TurnoService/CrearTurno',
            turnos__pb2.CrearTurnoRequest.SerializeToString,
            turnos__pb2.Turno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnos.TurnoService/ObtenerTurno',
            turnos__pb2.ObtenerTurnoRequest.SerializeToString,
            turnos__pb2.Turno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarTurnos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnos.TurnoService/ListarTurnos',
            turnos__pb2.ListarTurnosRequest.SerializeToString,
            turnos__pb2.ListaTurnos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReservarTurno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/turnos.TurnoService/ReservarTurno',
            turnos__pb2.ReservarTurnoRequest.SerializeToString,
            turnos__pb2.Turno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
